# Generated by Django 3.0.7 on 2020-07-01 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('url', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LaptopColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет (Ноутбук)',
                'verbose_name_plural': 'Цвета (Ноутбуки)',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LaptopCore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Процессор (Ноутбук)',
                'verbose_name_plural': 'Процессоры (Ноутбуки)',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LaptopOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Операционная система (ОС)')),
            ],
            options={
                'verbose_name': 'Операционная система (Ноутбук)',
                'verbose_name_plural': 'Операционные системы (Ноутбуки)',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LaptopRAMType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_type', models.CharField(max_length=50, verbose_name='Тип ОЗУ')),
            ],
            options={
                'verbose_name': 'Тип ОЗУ (Ноутбук)',
                'verbose_name_plural': 'Типы ОЗУ (Ноутбуки)',
                'ordering': ('ram_type',),
            },
        ),
        migrations.CreateModel(
            name='LaptopRefreshRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Частота обновлений экрана')),
            ],
            options={
                'verbose_name': 'Частота обновлений экрана (Ноутбук)',
                'verbose_name_plural': 'Список частот обновлений (Ноутбуки)',
                'ordering': ('value',),
            },
        ),
        migrations.CreateModel(
            name='LaptopScreenDiagonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150, verbose_name='Диагональ')),
            ],
            options={
                'verbose_name': 'Диагональ экрана (Ноутбук)',
                'verbose_name_plural': 'Список диагоналей (Ноутбуки)',
                'ordering': ('value',),
            },
        ),
        migrations.CreateModel(
            name='LaptopStorageSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveSmallIntegerField(verbose_name='Размер хранилища')),
            ],
            options={
                'verbose_name': 'Размер хранилища (Ноутбук)',
                'verbose_name_plural': 'Размеры хранилищ (Ноутбуки)',
                'ordering': ('size',),
            },
        ),
        migrations.CreateModel(
            name='LaptopStorageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type', models.CharField(max_length=50, verbose_name='Тип хранилища')),
            ],
            options={
                'verbose_name': 'Тип хранилища (Ноутбук)',
                'verbose_name_plural': 'Типы хранилищ (Ноутбуки)',
                'ordering': ('storage_type',),
            },
        ),
        migrations.CreateModel(
            name='LaptopStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Полное название')),
                ('storage_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.LaptopStorageSize', verbose_name='Размер хранилища')),
                ('storage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.LaptopStorageType', verbose_name='Тип хранилища')),
            ],
            options={
                'verbose_name': 'Хранилище (Ноутбук)',
                'verbose_name_plural': 'Хранилища (Ноутбуки)',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LaptopRAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Кол-во оперативной памяти (ОЗУ)')),
                ('ram_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.LaptopRAMType', verbose_name='Тип ОЗУ')),
            ],
            options={
                'verbose_name': 'Оперативная память (ОЗУ) (Ноутбук)',
                'verbose_name_plural': 'Список ОЗУ (Ноутбуи)',
                'ordering': ('value',),
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, max_length=200, verbose_name='Короткое описание')),
                ('url', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Картинка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('available', models.BooleanField(default=False, verbose_name='В наличии')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.Category')),
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptops', to='product.LaptopCore', verbose_name='Процессор')),
                ('diagonal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptops', to='product.LaptopScreenDiagonal', verbose_name='Диагональ экрана')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptops', to='product.LaptopOS', verbose_name='Операционная система')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptops', to='product.LaptopRAM', verbose_name='Оперативная память (ОЗУ)')),
                ('refresh_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptops', to='product.LaptopRefreshRate', verbose_name='Частота обновлений экрана')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptops', to='product.LaptopStorage', verbose_name='Тип хранилища')),
            ],
            options={
                'verbose_name': 'Ноутбук',
                'verbose_name_plural': 'Ноутбуки',
                'ordering': ('title',),
                'abstract': False,
                'index_together': {('id', 'url')},
            },
        ),
    ]
