# Generated by Django 3.0.7 on 2020-07-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_laptop_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptopram',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Полное название'),
        ),
    ]
